site_name: A Google Chart Sample
dev_addr: 0.0.0.0:8080
site_description: Examples of integrating MkDocs with 3rd Party Libraries.
site_author: Takuto Ochiai
site_url: http://ochi-taku.github.io/mkdocs03/
repo_url: https://github.com/ochi-taku/mkdocs03/
extra_javascript: []
extra_css: []
markdown_extensions: []
# git@github.com:katzkawai/mkdocs03.git
pages:
- ホーム: index.md
- 本サイトについて: about.md
- 自己紹介: profile.md
- 'サンプル': 'samples/index.md'
